# -*- coding: utf-8 -*-
"""notebook2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QbpPOf9rH4KJHr6S0DYsmag3_MnquXH3
"""

import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('gutenberg')
nltk.download('genesis')
nltk.download('inaugural')
nltk.download('nps_chat')
nltk.download('webtext')
nltk.download('treebank')
nltk.download('brown')
from nltk.book import *
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""text as a List of words"""

def lexical_diversity(text):
  return len(text)/len(set(text))

def percentage(count,total):
  return 100*count/total

sent1=['Lugbara','ti','is','the','highly','spoken','Language','in','Arua']
sent1

lexical_diversity(sent1)

sent2=['The', 'family', 'of', 'Dashwood', 'had', 'long',
'been', 'settled', 'in', 'Sussex', '.']
sent3=['In', 'the', 'beginning', 'God', 'created', 'the',
'heaven', 'and', 'the', 'earth', '.']
sorted(set(sent2))

sent2[1:4]

len(set(sent4))

fdist1=FreqDist(text1)
fdist1

fdist1.keys()

freq2=FreqDist(text2).keys()
freq2

fdist1.plot(50, cumulative=True)

"""finding words with characters more than 15 Characters"""

V=set(text1)
long_words=[w for w in V if len(w)>15]
sorted(long_words)

x=set(text2)
lng=[i for i in x if len(i)>15]
lng

fdist3=FreqDist(text5)
sorted([w for w in set(text5) if len(w)>7 and fdist3[w]>7])